# These substitutions allow the end user to override certain values
substitutions:
  name: "project-template"
  friendly_name: "Project Template"

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  
  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: wittronics.dev-template
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dashboard_import:
  package_import_url: github://Wisje/RoomSensor/dev-template.yaml
  import_full_config: false

wifi:
  # ssid: "WitTronics-Guest"
  # password: "JSWitteveen"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dev Fallback Hotspot"
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:


  

esp32_improv:
  authorizer: none

improv_serial:
